export interface Language {
  code: string;
  name: string;
}

export const languages: Language[] = [
  { code: 'AC', name: 'Araucanian' },
  { code: 'AD', name: 'Adangme' },
  { code: 'AE', name: 'Afroasiatic' },
  { code: 'AF', name: 'Afrikaans' },
  { code: 'AH', name: 'Amharic (aka Ethiopian)' },
  { code: 'AJ', name: 'Acholi' },
  { code: 'AK', name: 'Akan' },
  { code: 'AL', name: 'Albanian' },
  { code: 'AM', name: 'Armenian' },
  { code: 'AO', name: 'Chinese' },
  { code: 'AR', name: 'Arabic' },
  { code: 'AS', name: 'Assamese' },
  { code: 'AW', name: 'Arawak' },
  { code: 'AY', name: 'Aymara' },
  { code: 'AZ', name: 'Azerbaijani (aka Azeri)' },
  { code: 'BA', name: 'Balante' },
  { code: 'BB', name: 'Bemba' },
  { code: 'BE', name: 'Belorussian' },
  { code: 'BG', name: 'Bengali (Bangla)' },
  { code: 'BH', name: 'Bhili' },
  { code: 'BI', name: 'Bihari' },
  { code: 'BL', name: 'Baluchi' },
  { code: 'BM', name: 'Bambara' },
  { code: 'BO', name: 'Bosnian' },
  { code: 'BQ', name: 'Basque' },
  { code: 'BR', name: 'Brahui' },
  { code: 'BS', name: 'Burmese' },
  { code: 'BT', name: 'Breton' },
  { code: 'BU', name: 'Bulgarian' },
  { code: 'BX', name: 'Bassa' },
  { code: 'BY', name: 'Balinese' },
  { code: 'CA', name: 'Cham' },
  { code: 'CB', name: 'Cebuano' },
  { code: 'CE', name: 'Chinese' },
  { code: 'CH', name: 'Chinese' },
  { code: 'CJ', name: 'Chechen' },
  { code: 'CN', name: 'Chinese' },
  { code: 'CS', name: 'Chinese' },
  { code: 'CT', name: 'Catalan' },
  { code: 'CU', name: 'Chuukese (Trukese)' },
  { code: 'CZ', name: 'Czech' },
  { code: 'DA', name: 'Dari/Farsi/Persian' },
  { code: 'DG', name: 'Dagomba' },
  { code: 'DJ', name: 'Dyula' },
  { code: 'DN', name: 'Danish' },
  { code: 'DU', name: 'Dutch' },
  { code: 'DZ', name: 'Dzongkha' },
  { code: 'ED', name: 'Edo (Bini)' },
  { code: 'EG', name: 'Guyanese Creole' },
  { code: 'EO', name: 'Estonian' },
  { code: 'EW', name: 'Ewe' },
  { code: 'FG', name: 'Guianese Creole (Guyanais/French- based)' },
  { code: 'FH', name: 'Haitian Creole' },
  { code: 'FJ', name: 'Fijian' },
  { code: 'FK', name: 'French-Khmer' },
  { code: 'FL', name: 'Flemish' },
  { code: 'FN', name: 'Finnish' },
  { code: 'FO', name: 'Fon' },
  { code: 'FR', name: 'French' },
  { code: 'FT', name: 'Fanti (aka Fante)' },
  { code: 'FU', name: 'Fulani' },
  { code: 'GA', name: 'Ga' },
  { code: 'GC', name: 'Galician' },
  { code: 'GE', name: 'Georgian' },
  { code: 'GF', name: 'Garifuna' },
  { code: 'GI', name: 'Gilbertese (Kiribati/Kiribatese)' },
  { code: 'GJ', name: 'Gujarati' },
  { code: 'GK', name: 'Greek' },
  { code: 'GL', name: 'Galla' },
  { code: 'GM', name: 'Gurma' },
  { code: 'GO', name: 'Grebo' },
  { code: 'GR', name: 'German' },
  { code: 'GU', name: 'Guarani' },
  { code: 'HA', name: 'Haitian Creole' },
  { code: 'HE', name: 'Hebrew' },
  { code: 'HG', name: 'Hungarian' },
  { code: 'HI', name: 'Hindi' },
  { code: 'HM', name: 'Hmong' },
  { code: 'HN', name: 'Mina (Hina/Besleri)' },
  { code: 'HU', name: 'Hausa (Haoussa)' },
  { code: 'IB', name: 'Ibo' },
  { code: 'IC', name: 'Icelandic' },
  { code: 'IL', name: 'Ilocano' },
  { code: 'IN', name: 'Indonesian (aka Bahasa)' },
  { code: 'IR', name: 'Irish (Gaelic)' },
  { code: 'IT', name: 'Italian' },
  { code: 'JA', name: 'Japanese' },
  { code: 'JI', name: 'Pijin (Solomons Pidgin)' },
  { code: 'JM', name: 'Jamaican-Creole' },
  { code: 'JO', name: 'Johkha' },
  { code: 'KA', name: 'Kashmiri' },
  { code: 'KB', name: 'Kamba' },
  { code: 'KC', name: 'Kachi' },
  { code: 'KD', name: 'Kannada' },
  { code: 'KE', name: 'Kabre' },
  { code: 'KF', name: 'Kafiri' },
  { code: 'KG', name: 'Kanarese' },
  { code: 'KH', name: 'Khmer (Cambodge)' },
  { code: 'KI', name: 'Kikuyu' },
  { code: 'KK', name: 'Krio' },
  { code: 'KM', name: 'Akaselem (Tchamba/Chamba)' },
  { code: 'KN', name: 'Kanuri' },
  { code: 'KO', name: 'Korean' },
  { code: 'KP', name: 'Kpelle' },
  { code: 'KQ', name: 'Kaqchikel (Cakchiquel/Cachiquel)' },
  { code: 'KR', name: 'Karen' },
  { code: 'KS', name: 'Khoisan' },
  { code: 'KU', name: 'Kurdish' },
  { code: 'KW', name: 'Khowan' },
  { code: 'KY', name: 'Kabyle' },
  { code: 'KZ', name: 'Kazakh' },
  { code: 'LA', name: 'Lao' },
  { code: 'LG', name: 'Luganda' },
  { code: 'LM', name: 'Loma' },
  { code: 'LN', name: 'Lingala' },
  { code: 'LO', name: 'Luo' },
  { code: 'LT', name: 'Lithuanian' },
  { code: 'LU', name: 'Luba' },
  { code: 'LV', name: 'Latvian' },
  { code: 'LY', name: 'Lunyankole' },
  { code: 'MA', name: 'Macedonian' },
  { code: 'MB', name: 'Mandinka (aka Mandingo)' },
  { code: 'MD', name: 'Moldavian' },
  { code: 'ME', name: 'Mende' },
  { code: 'MG', name: 'Malagasy' },
  { code: 'MH', name: 'Mohawk' },
  { code: 'MI', name: 'Mongolian' },
  { code: 'MK', name: 'Malinke' },
  { code: 'ML', name: 'Malay' },
  { code: 'MM', name: 'Mam' },
  { code: 'MN', name: 'Chinese' },
  { code: 'MO', name: 'Mossi (Moore/More)' },
  { code: 'MP', name: 'Manipuri (Meitei/Meiteilon)' },
  { code: 'MR', name: 'Marathi' },
  { code: 'MS', name: 'Miskito (Miskitu)' },
  { code: 'MT', name: 'Maltese' },
  { code: 'MX', name: 'Mixtec (Mixteco)' },
  { code: 'MY', name: 'Malayalam' },
  { code: 'NA', name: 'Nahuatl' },
  { code: 'NC', name: 'Niger-Congo' },
  { code: 'ND', name: 'Ndebele' },
  { code: 'NE', name: 'Nepali' },
  { code: 'NL', name: 'Native American Languages' },
  { code: 'NO', name: 'English' },
  { code: 'NS', name: 'Student Does Not Speak' },
  { code: 'NU', name: 'Nauru (Nauruan)' },
  { code: 'NW', name: 'Norwegian' },
  { code: 'NY', name: 'Nyanja (aka Chinyanja)' },
  { code: 'ON', name: 'Oneida' },
  { code: 'OR', name: 'Oriya' },
  { code: 'OS', name: 'Ossetian' },
  { code: 'PA', name: 'Pashto (aka Pushto)' },
  { code: 'PI', name: 'Pilipino (aka Tagalog)' },
  { code: 'PJ', name: 'Punjabi (aka Panjabi)' },
  { code: 'PL', name: 'Polish' },
  { code: 'PN', name: 'Palauan' },
  { code: 'PO', name: 'Portuguese' },
  { code: 'PP', name: 'Papiamento' },
  { code: 'PR', name: 'Provencal' },
  { code: 'QC', name: 'Quiche' },
  { code: 'QU', name: 'Quechua' },
  { code: 'RA', name: 'Rajasthani' },
  { code: 'RD', name: 'Rundi' },
  { code: 'RK', name: 'Rakhine (Arakense)' },
  { code: 'RM', name: 'Romansch' },
  { code: 'RO', name: 'Romanian' },
  { code: 'RT', name: 'Tooro (Rutooro)' },
  { code: 'RU', name: 'Russian' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'RY', name: 'Russian-Yiddish' },
  { code: 'SA', name: 'Samoan' },
  { code: 'SB', name: 'Shina' },
  { code: 'SC', name: 'Serbo-Croatian' },
  { code: 'SD', name: 'Sindhi' },
  { code: 'SE', name: 'Seneca' },
  { code: 'SF', name: 'Sinhalese' },
  { code: 'SG', name: 'Scottish-Gaelic' },
  { code: 'SH', name: 'Shan' },
  { code: 'SI', name: 'Swahili (aka Kiswahili)' },
  { code: 'SJ', name: 'Somali' },
  { code: 'SK', name: 'Sukuma' },
  { code: 'SL', name: 'Shluh' },
  { code: 'SM', name: 'Sidamo' },
  { code: 'SN', name: 'Sanskrit' },
  { code: 'SO', name: 'Slovak' },
  { code: 'SP', name: 'Spanish' },
  { code: 'SQ', name: 'Soninke' },
  { code: 'SR', name: 'Seri' },
  { code: 'SS', name: 'Setswana' },
  { code: 'ST', name: 'Sesotho' },
  { code: 'SU', name: 'Sudanese' },
  { code: 'SV', name: 'Slovenian' },
  { code: 'SW', name: 'Swedish' },
  { code: 'SX', name: '(American) Sign Language' },
  { code: 'SY', name: 'South Arabic' },
  { code: 'SZ', name: 'Swazi' },
  { code: 'TA', name: 'Tamil' },
  { code: 'TB', name: 'Tem (Temba/Kotokoli/Cotocoli)' },
  { code: 'TE', name: 'Telugu' },
  { code: 'TG', name: 'Tigre' },
  { code: 'TH', name: 'Thai' },
  { code: 'TI', name: 'Tibetan' },
  { code: 'TK', name: 'Turkmen (Turkman/Turkoman)' },
  { code: 'TM', name: 'Tamazight' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TQ', name: 'Tamasheq' },
  { code: 'TR', name: 'Tigrinya' },
  { code: 'TT', name: 'Tuareg' },
  { code: 'TU', name: 'Turkish' },
  { code: 'TW', name: 'Twi' },
  { code: 'TZ', name: 'Tadzhik (aka Tajik)' },
  { code: 'UD', name: 'Urdu' },
  { code: 'UH', name: 'Urhobo' },
  { code: 'UI', name: 'Uighur (Uyghur)' },
  { code: 'UR', name: 'Ukrainian' },
  { code: 'US', name: 'Susu (Soussou)' },
  { code: 'UZ', name: 'Uzbek' },
  { code: 'VC', name: 'Vietnamese' },
  { code: 'VF', name: 'Vietnamese' },
  { code: 'VN', name: 'Vietnamese' },
  { code: 'VS', name: 'Visayak (aka Bisaya)' },
  { code: 'WE', name: 'Welsh' },
  { code: 'WO', name: 'Wolof' },
  { code: 'YI', name: 'Yiddish' },
  { code: 'YL', name: 'Sylheti' },
  { code: 'YO', name: 'Yonba' },
  { code: 'YR', name: 'Yoruba' },
  { code: 'ZA', name: 'Zarma (Djerma)' },
  { code: 'ZU', name: 'Zulu' },
];
